Repository ServiceInnovationLab/PresenceChecker, pull requests merged in 2018-12, with the labels that each got.

#102 Fix logout links
  config/initializers/devise.rb
Labels: review

#79 Front-end UI
  .codeclimate.yml
  Gemfile
  Gemfile.lock
  README.md
  app/assets/javascripts/clients.coffee
  app/assets/javascripts/identities.coffee
  app/assets/stylesheets/application.css
  app/assets/stylesheets/clients.scss
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/home.css
  app/assets/stylesheets/identities.scss
  app/assets/stylesheets/lists.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/utils.scss
  app/controllers/clients_controller.rb
  app/controllers/hello_world_controller.rb
  app/controllers/home_controller.rb
  app/controllers/identities_controller.rb
  app/helpers/clients_helper.rb
  app/helpers/identities_helper.rb
  app/helpers/movements_helper.rb
  app/javascript/bundles/HelloWorld/components/HelloWorld.jsx
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/javascript/packs/hello-world-bundle.js
  app/models/identity.rb
  app/views/clients/_form.html.erb
  app/views/clients/show.html.erb
  app/views/hello_world/index.html.erb
  app/views/home/index.html.erb
  app/views/identities/_search.html.erb
  app/views/identities/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/hello_world.html.erb
  app/views/movements/index.html.erb
  app/views/movements/show.html.erb
  config/routes.rb
  db/migrate/20181205024431_create_identities.rb
  db/migrate/20181205025832_create_movements.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/clients_controller_spec.rb
  spec/controllers/identities_controller_spec.rb
  test/factories/clients.rb
  test/factories/countries.rb
  test/factories/identities.rb
  test/factories/movements.rb
Labels: review

#95 Inviting users to the system -- and creating in db:seed
  Gemfile
  Gemfile.lock
  app/controllers/clients_controller.rb
  app/models/user.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise_invitable.en.yml
  db/migrate/20181206043729_devise_invitable_add_to_users.rb
  db/schema.rb
  db/seeds.rb
Labels: review

#108 Auto corrected by following Javascript quotes
  app/javascript/packs/hello-world-bundle.js
Labels: review

#96 Editing of users
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/users/index.html.haml
  config/routes.rb
Labels: review

#116 Feature/111 data in app matches design
  app/assets/stylesheets/components.scss
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/models/identity.rb
  app/views/clients/show.html.erb
  app/views/identities/_search.html.erb
Labels: review

#113 Specs for models and controllers
  Gemfile
  Gemfile.lock
  spec/controllers/clients_controller_spec.rb
  spec/controllers/identities_controller_spec.rb
  spec/models/client_spec.rb
  spec/models/country_spec.rb
  spec/models/identity_spec.rb
  test/factories/identities.rb
Labels: review

#121 Feature/email
  app.json
  config/environments/production.rb
Labels: review

#118 add a menu
  app/assets/stylesheets/components.scss
  app/views/layouts/_header.html.erb
Labels: review

#115 Feature/presence
  app/assets/javascripts/clients.coffee
  app/assets/javascripts/identities.coffee
  app/assets/stylesheets/application.css
  app/assets/stylesheets/clients.scss
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/identities.scss
  app/assets/stylesheets/react-datepicker-cssmodules.min.css
  app/assets/stylesheets/react-datepicker.min.css
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/utils.scss
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/javascript/bundles/Presence/components/EligibilityDates.jsx
  app/javascript/bundles/Presence/components/PresenceDebugger.jsx
  app/javascript/bundles/Presence/components/PresenceTable.jsx
  app/javascript/bundles/Presence/components/TimePeriod.jsx
  app/javascript/bundles/Presence/components/Year.jsx
  app/javascript/bundles/PresenceDebugger/components/EligibilityDates.jsx
  app/javascript/bundles/PresenceDebugger/components/PresenceDebugger.jsx
  app/javascript/bundles/PresenceDebugger/components/TimePeriod.jsx
  app/javascript/packs/hello-world-bundle.js
  app/views/clients/_form.html.erb
  app/views/clients/_movement.html.erb
  app/views/clients/show.html.erb
  app/views/movements/index.html.erb
  app/views/movements/show.html.erb
  db/seeds.rb
  package.json
  yarn.lock
Labels: review

#144 Feature/style menu
  app/assets/stylesheets/components.scss
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
Labels: review

#145 center align presence table contents
  app/assets/stylesheets/components.scss
Labels: review

#142 Swapping the install order of yarn and bundle
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.scss
Labels: review

#153 User should not be able to delete themselves
  app/controllers/users_controller.rb
  app/views/users/index.html.haml
  spec/views/users/index.html.haml_spec.rb
Labels: review

#127 Auto corrected by following Javascript quotes
  app/javascript/packs/hello-world-bundle.js
Labels: development, review

#151 If one result, redirect to client#show
  app/controllers/identities_controller.rb
  spec/controllers/identities_controller_spec.rb
Labels: development, good first issue, railsy, review

#152 Bugfix/100 turn off sign up
  app/models/user.rb
  app/views/devise/shared/_links.html.erb
  config/locales/devise.en.yml
  spec/controllers/devise/users_controller_spec.rb
Labels: review

#141 REMOVED: duplicate Components
  app/assets/stylesheets/colours.scss
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/utils.scss
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Presence/components/EligibilityDates.jsx
  app/javascript/bundles/Presence/components/PresenceDebugger.jsx
  app/javascript/bundles/Presence/components/PresenceTable.jsx
  app/javascript/bundles/Presence/components/TimePeriod.jsx
  app/javascript/bundles/Presence/components/Year.jsx
  app/javascript/bundles/PresenceDebugger/components/EligibilityDates.jsx
Labels: review

#158 Auto corrected by following Ruby MagicComment
  spec/views/users/index.html.haml_spec.rb
Labels: review

#161 Feature/143 dry front end
  .codeclimate.yml
  .editorconfig
  .eslintrc
  app/assets/javascripts/cable.js
  app/javascript/bundles/HelloWorld/components/HelloWorld.jsx
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/javascript/bundles/Presence/components/EligibilityDates.jsx
  app/javascript/bundles/Presence/components/PresenceDates.jsx
  app/javascript/bundles/Presence/components/PresenceTable.jsx
  app/javascript/bundles/Presence/components/Year.jsx
  app/javascript/bundles/PresenceDebugger/components/TimePeriod.jsx
  app/javascript/components/EligibilityDates.jsx
  app/javascript/components/PresenceDebugger.jsx
  app/javascript/components/Table.jsx
  app/javascript/components/TimePeriod.jsx
  app/javascript/packs/application.js
  app/javascript/packs/hello-world-bundle.js
  app/javascript/packs/hello_react.jsx
  app/views/layouts/application.html.erb
  app/views/layouts/hello_world.html.erb
Labels: review

#162 Feature/119 show issuing state
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/models/identity.rb
  app/views/clients/show.html.erb
Labels: review

#166 Update design
  app/assets/stylesheets/colours.scss
  app/assets/stylesheets/components.scss
  app/javascript/bundles/Presence/components/PresenceDates.jsx
  app/javascript/components/EligibilityDates.jsx
  app/javascript/packs/application.js
Labels: review

#168 Feature/db seeds
  db/seeds.rb
Labels: review

#170 Expose service endpoint
  app/controllers/clients_controller.rb
  app/javascript/packs/application.js
  config/routes.rb
Labels: review

#167 Add heroku deploy key to Travis
  .travis.yml
Labels: review

#171 Auto corrected by following Ruby EmptyLine
  spec/services/eligibility_service_spec.rb
Labels: review

#176 Delegate some model properties
  app/models/identity.rb
Labels: review

#174 Adding in meet_preceeding_single_year_minimum_presence_requirement
  app/services/eligibility_service.rb
Labels: review

#179 Add openfisca default url to app.json
  app.json
Labels: review

#178 Auto corrected by following Ruby RSpecEmptyLine
  spec/services/eligibility_service_spec.rb
Labels: review

#185 Two eligible people (improve db:seeds)
  db/seeds.rb
Labels: review

#187 Feature/movements table
  app/assets/stylesheets/colours.scss
  app/assets/stylesheets/components.scss
  app/javascript/bundles/Presence/components/MovementsTable.jsx
  app/javascript/packs/application.js
  app/views/clients/show.html.erb
Labels: review

#189 add emails to seed data
  db/seeds.rb
Labels: review

#191 Movements table scroll container
  app/assets/stylesheets/components.scss
  app/javascript/bundles/Presence/components/MovementsTable.jsx
Labels: review

#194 added .env file instructions to readme
  README.md
Labels: review

#201 update client_id and identity number
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/views/clients/show.html.erb
Labels: review

#190 Data in shape the reactcomponents expect
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/keyframes.scss
  app/controllers/clients_controller.rb
  app/javascript/bundles/Presence/components/MovementsTable.jsx
  app/javascript/bundles/Presence/components/PresenceDates.jsx
  app/javascript/bundles/Presence/components/PresenceTable.jsx
  app/javascript/bundles/Presence/components/Year.jsx
  app/javascript/components/Table.jsx
  app/javascript/packs/application.js
  app/javascript/utilities/utilities.js
  app/services/eligibility_service.rb
  app/views/clients/show.html.erb
  config/routes.rb
  spec/controllers/clients_controller_spec.rb
Labels: review

#205 Calendar of future eligible days
  app/javascript/packs/application.js
Labels: review

#210 Small update to clarify what Travis does to deploy the app
  README.md
Labels: review

#209 Auto corrected by following Ruby Layout/TrailingWhitespace
  Gemfile
Labels: review

#186 Auto corrected by following Ruby EmptyLine
  spec/services/eligibility_service_spec.rb
Labels: Tech debt, review

#204 Enforce half decent passwords
  app/models/user.rb
  spec/models/user_spec.rb
  test/factories/users.rb
Labels: review

#192 convert erb files to haml
  app/assets/stylesheets/components.scss
  app/views/clients/_movement.html.erb
  app/views/hello_world/index.html.erb
  app/views/identities/_search.html.erb
  app/views/identities/_search.html.haml
  app/views/identities/index.html.erb
  app/views/identities/index.html.haml
  app/views/layouts/_header.html.erb
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.haml
  app/views/layouts/hello_world.html.erb
  spec/views/identities/_search.html.haml_spec.rb
  spec/views/identities/index.html.haml_spec.rb
  spec/views/layouts/_header.html.haml_spec.rb
  spec/views/layouts/application.html.haml_spec.rb
Labels: Tech debt, review

#211 pass through more data from controller and map more explicitly in react
  app/controllers/clients_controller.rb
  app/javascript/bundles/Presence/components/PresenceTable.jsx
  db/seeds.rb
  spec/controllers/clients_controller_spec.rb
Labels: review

#215 Auto corrected by following Ruby Style/StringLiterals
  spec/services/eligibility_service_spec.rb
Labels: review

#213 Auto corrected by following Ruby EmptyLine
  spec/views/layouts/_header.html.haml_spec.rb
  spec/views/layouts/application.html.haml_spec.rb
Labels: review

#220 Jest coverage
  .babelrc
  .travis.yml
  app/javascript/bundles/Identity/components/Identity.jsx
  app/javascript/bundles/Identity/components/KnownIdentity.jsx
  app/javascript/bundles/Presence/components/MovementsTable.jsx
  app/javascript/components/TimePeriod.jsx
  app/javascript/packs/application.js
  app/javascript/utilities/utilities.js
  package.json
  spec/javascript/bundles/Identity/components/Identity.test.js
  spec/javascript/bundles/Identity/components/KnownIdentity.test.js
  spec/javascript/bundles/Presence/components/MovementsTable.test.js
  spec/javascript/bundles/Presence/components/PresenceDates.test.js
  spec/javascript/bundles/Presence/components/PresenceTable.test.js
  spec/javascript/bundles/Presence/components/Year.test.js
  spec/javascript/components/PresenceDebugger.test.js
  spec/javascript/components/Table.test.js
  spec/javascript/components/TimePeriod.test.js
  spec/javascript/packs/application.test.js
  spec/javascript/utilities/utilities.test.js
  yarn.lock
Labels: review

#226 Auto corrected by following Javascript Space
  spec/javascript/packs/application.test.js
Labels: review

#228 Auto corrected by following Javascript semi
  spec/javascript/bundles/Identity/components/Identity.test.js
  spec/javascript/components/PresenceDebugger.test.js
  spec/javascript/components/TimePeriod.test.js
Labels: review

#230 remove word serial and replace with passport
  app/views/identities/index.html.haml
Labels: review

#214 Pre fetch data, save in a model
  app/controllers/clients_controller.rb
  app/models/client.rb
  app/models/eligibility.rb
  app/models/movement.rb
  app/services/eligibility_service.rb
  app/views/clients/show.html.erb
  db/migrate/20181213000738_create_eligibilities.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/clients.rake
  spec/controllers/clients_controller_spec.rb
  spec/services/eligibility_service_spec.rb
  test/factories/eligibilities.rb
Labels: review
